version: '3.8'

services:
  # Service pour l'application Spring Boot
  app:
    build: .
    image: backend:1.0
    ports:
      - "9090:9090"  # Map le port 8080 de l'hôte vers le port 8080 du conteneur
