name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Vérifier le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Authentification à Azure avec az login
      - name: Log in to Azure
        run: |
          az login --username ${{ secrets.AZURE_USERNAME }} --password ${{ secrets.AZURE_PASSWORD }}

      # 4. Authentification à Azure Container Registry (ACR)
      - name: Log in to ACR
        run: |
          az acr login --name acr1zbr89sm

      # 5. Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t acr1zbr89sm.azurecr.io/api:1.0.0 .

      # 6. Pousser l'image vers ACR
      - name: Push Docker image to ACR
        run: |
          docker push acr1zbr89sm.azurecr.io/api:1.0.0
